version: '3'
services:

  sudfda_client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public

  sudfa_server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    network_mode: host
    ports:
      - "5000:5000"
    volumes:
      - ./server/.env:/usr/src/app/.env
      - ./server/src:/usr/src/app/src
      - ./server/server.js:/usr/src/app/server.js
    depends_on:
      - sudfa_pg

  sudfa_arena:
    build:
      context: ./arena
      dockerfile: dev.Dockerfile
    network_mode: host
    ports:
      - "5001:5001"
    volumes:
      - ./arena/.env:/usr/src/app/.env
      - ./arena/src:/usr/src/app/src
      - ./arena/index.js:/usr/src/app/index.js

  sudfa_pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data

